### ISSUE TITLE
Problems with InternalModes and constant stratification

### ISSUE THREAD

**Issue by NeilTandon** [JeffreyEarly/GLOceanKit#16]
I haven't been able to get InternalModes to work with constant stratification. The first issue I encountered was because the first argument fed to InternalModesConstantStratification is [N0, min(rho(zIn))], but rho is typically a function handle, so min(rho) returns an error. I attempted to fix this by replacing min(rho) with min(rho(zIn)) . So that error is gone, but now I get the following output:

```
Initialization detected that you are using constant stratification. The modes will now be computed using the analytical form. If you would like to override this behavior, specify the method parameter.
Using the analytical form for constant stratification N0=0.006777884
Error using .*
Matrix dimensions must agree.

Error in InternalModesConstantStratification/BaroclinicModesWithEigenvalue (line 146)
            G = A .*  sin(k_z .* (self.z + self.Lz));

Error in InternalModesConstantStratification/ModesAtFrequency (line 79)
            [F,G] = self.BaroclinicModesWithEigenvalue(k_z,h);

Error in InternalModes/ModesAtFrequency (line 419)
            [F,G,h,k] = self.internalModes.ModesAtFrequency( omega );

Error in batch85b_modal_decomp_ECCO (line 163)
    [Ftmp,G,h,k] = im.ModesAtFrequency(omega);
```

**Comment by JeffreyEarly** [comment]
I'm confused, what exactly are you feeding into InternalModesConstantStratification?

I'm trying,
```matlab
z = linspace(-5000, 0, 128)';
im = InternalModesConstantStratification([5.2e-3 1025], [-5000 0], z, 35);
[F,G,h,k] = im.ModesAtFrequency(im.f0);
```

**Comment by NeilTandon** [comment]
Sorry, I should have provided more detail. Here is a simple code that produces the error I mentioned above:

```
N0 = 5.2e-3;
g = 9.81;
rho0 = 1025;
rho = @(z) -(N0*N0*rho0/g)*z + rho0;
L = -5000;
zOut = linspace(L,0,200)';
latitude = 33;
im = InternalModes(rho,[L 0],zOut,latitude);
[F,G,h,k] = im.ModesAtFrequency(5*im.f0);
```
The error is produced by the last command, im.ModesAtFrequency. When using constant stratification, is that the right command for obtaining F and G?

**Comment by JeffreyEarly** [comment]
Thank you! That let me repeat the error. I just updated the code with a fix---trying pulling the changes and see if that fixes it for you.

**Comment by NeilTandon** [comment]
Re-downloaded the code, but still getting the same error. :(
BTW, I'm using MATLAT R2013b, in case that matters.

**Comment by JeffreyEarly** [comment]
Ah ha! Matlab 2013b is the problem---I'm using the new (as of 2016b) array [expansion operators](https://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/). Shoot---any chance you can easily upgrade?

**Comment by JeffreyEarly** [comment]
Yes, there's definitely no problem overriding it to use wkbAdaptiveSpectral. The only real compromise is speed... and that you have to watch out for garbage modes that might occur, but it's generally quite good, especially in smooth stratification profiles.
